XTrain = digitTrainCellArrayData;
%XTrain = XTrain (1:500);
hiddenSize = 400;
autoenc = trainAutoencoder(XTrain,hiddenSize,...
        'L2WeightRegularization',0.004,...
        'SparsityRegularization',4,...
        'SparsityProportion',0.15);
feat1 = encode(autoenc1,XTrain);
hiddenSize2 = 50;
autoenc2 = trainAutoencoder(feat1,hiddenSize2, ...
    'L2WeightRegularization',0.004, ...
    'SparsityRegularization',4, ...
    'SparsityProportion',0.1, ...
    );
XTest = digitTestCellArrayData;

