digitDatasetPath = fullfile("/Users/kasik2/Documents/Soil Playground/Hcube_Unreduced_Classified");
imds = imageDatastore(digitDatasetPath, ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames', "FileExtensions",".mat");
imds.ReadFcn = @ExtractCube;
